/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import model.User;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import java.io.File;
import java.awt.Image;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author demi
 */
public class profile extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(profile.class.getName());

    /**
     * Creates new form profile
     */
    private File selectedPhoto;
    public profile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StudentProfile = new javax.swing.JLabel();
        FirstName = new javax.swing.JLabel();
        FirstNameTextField = new javax.swing.JTextField();
        LastName = new javax.swing.JLabel();
        LastNameTextField = new javax.swing.JTextField();
        Gender = new javax.swing.JLabel();
        Age = new javax.swing.JLabel();
        Phone = new javax.swing.JLabel();
        PhoneTextField = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        EmailTextField = new javax.swing.JTextField();
        Continent = new javax.swing.JLabel();
        Hobbies = new javax.swing.JLabel();
        HobbiesTextField = new javax.swing.JTextField();
        GenderComboBox = new javax.swing.JComboBox<>();
        AgeSpinner = new javax.swing.JSpinner();
        ContinentComboBox = new javax.swing.JComboBox<>();
        UploadButton = new javax.swing.JButton();
        SubmitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        StudentProfile.setText("Student Profile");

        FirstName.setText("First Name:");

        FirstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameTextFieldActionPerformed(evt);
            }
        });

        LastName.setText("Last Name:");

        Gender.setText("Gender:");

        Age.setText("Age:");

        Phone.setText("Phone:");

        PhoneTextField.setToolTipText("123-456-7890");

        Email.setText("Email:");

        Continent.setText("Continent:");

        Hobbies.setText("Hobbies:");

        GenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));

        ContinentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Africa", "Antarctica", "Asia", "Europe", "North America", "South America", "Australia" }));

        UploadButton.setText("Upload");
        UploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadButtonActionPerformed(evt);
            }
        });

        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(FirstName)
                        .addGap(18, 18, 18)
                        .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(StudentProfile))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LastName)
                            .addComponent(Gender)
                            .addComponent(Age)
                            .addComponent(Phone)
                            .addComponent(Email)
                            .addComponent(Continent)
                            .addComponent(Hobbies))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ContinentComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HobbiesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(EmailTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PhoneTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AgeSpinner, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LastNameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GenderComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(147, 147, 147)))))
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UploadButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SubmitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(136, 136, 136))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StudentProfile)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstName)
                    .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastName)
                    .addComponent(LastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Gender)
                    .addComponent(GenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Age)
                    .addComponent(AgeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Phone)
                    .addComponent(PhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email)
                    .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Continent)
                    .addComponent(ContinentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HobbiesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hobbies))
                .addGap(18, 18, 18)
                .addComponent(UploadButton)
                .addGap(18, 18, 18)
                .addComponent(SubmitButton)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FirstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameTextFieldActionPerformed

    private void UploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadButtonActionPerformed

        JFileChooser    chooser = new JFileChooser();
                    chooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
                    "Image Files", "jpg", "jpeg", "gif"));
                    if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                        selectedPhoto = chooser.getSelectedFile();
                        JOptionPane.showMessageDialog(this,
                                "Selected: " + selectedPhoto.getName());
                    }
        // TODO add your handling code here:
    }//GEN-LAST:event_UploadButtonActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
              submitForm();

    }
 
    private void submitForm() {

        // Read input

        String firstname = FirstNameTextField.getText().trim();

        String lastname = LastNameTextField.getText().trim();

        String gender = GenderComboBox.getSelectedItem().toString();

        int age = (Integer) AgeSpinner.getValue();

        String phone = PhoneTextField.getText().trim();

        String email = EmailTextField.getText().trim();

        String continent = ContinentComboBox.getSelectedItem().toString();

        String hobbies = HobbiesTextField.getText().trim();
 
        // Validation

        if (firstname.isEmpty() || lastname.isEmpty() || phone.isEmpty() || email.isEmpty()) {

            JOptionPane.showMessageDialog(this, "Please fill all required fields.", "Error", JOptionPane.ERROR_MESSAGE);

            return;

        }
 
        String phoneDigits = phone.replaceAll("\\D", "");

        if (phoneDigits.length() < 8) {

            JOptionPane.showMessageDialog(this, "Phone number must have at least 8 digits.", "Error", JOptionPane.ERROR_MESSAGE);

            return;

        }
 
        if (!email.matches("^[\\w.-]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {

            JOptionPane.showMessageDialog(this, "Invalid email format.", "Error", JOptionPane.ERROR_MESSAGE);

            return;

        }
 
        // Create User object

        User user = new User(firstname, lastname, gender, age, phone, email, continent, hobbies, selectedPhoto);
 
        // Show user info

        if (selectedPhoto != null) {

            ImageIcon icon = new ImageIcon(

                    new ImageIcon(selectedPhoto.getAbsolutePath())

                            .getImage().getScaledInstance(120, 120, java.awt.Image.SCALE_SMOOTH)

            );

            JOptionPane.showMessageDialog(this, user.toString(), "Profile", JOptionPane.INFORMATION_MESSAGE, icon);

        } else {

            JOptionPane.showMessageDialog(this, user.toString(), "Profile", JOptionPane.INFORMATION_MESSAGE);

        }

 
    }//GEN-LAST:event_SubmitButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new profile().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Age;
    private javax.swing.JSpinner AgeSpinner;
    private javax.swing.JLabel Continent;
    private javax.swing.JComboBox<String> ContinentComboBox;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JLabel FirstName;
    private javax.swing.JTextField FirstNameTextField;
    private javax.swing.JLabel Gender;
    private javax.swing.JComboBox<String> GenderComboBox;
    private javax.swing.JLabel Hobbies;
    private javax.swing.JTextField HobbiesTextField;
    private javax.swing.JLabel LastName;
    private javax.swing.JTextField LastNameTextField;
    private javax.swing.JLabel Phone;
    private javax.swing.JTextField PhoneTextField;
    private javax.swing.JLabel StudentProfile;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JButton UploadButton;
    // End of variables declaration//GEN-END:variables
}
